# Generated by Django 5.1.6 on 2025-02-08 09:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='hire_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employees',
            name='skills',
            field=models.ManyToManyField(related_name='compétences', to='employees.skill'),
        ),
    ]
