# Generated by Django 5.1.6 on 2025-02-08 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employees_hire_date_alter_employees_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cv/'),
        ),
    ]
